create table if not exists public.solicitudes_demo (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  nombre text not null,
  email text not null,
  telefono text,
  negocio text,
  producto text,
  plan_interes text,
  mensaje text,
  estado text not null default 'pendiente',
  origen text not null default 'web',
  leida boolean not null default false
);

alter table public.solicitudes_demo enable row level security;

do $$
begin
  create policy "Permitir insertar solicitudes demo desde web"
  on public.solicitudes_demo
  for insert
  to anon
  with check (
    nombre is not null
    and length(trim(nombre)) > 0
    and email is not null
    and length(trim(email)) > 3
  );
exception
  when duplicate_object then
    null;
end
$$;

create index if not exists idx_solicitudes_demo_created_at
on public.solicitudes_demo (created_at desc);

create index if not exists idx_solicitudes_demo_estado
on public.solicitudes_demo (estado);

create index if not exists idx_solicitudes_demo_leida
on public.solicitudes_demo (leida);

-- No crear policy SELECT publica.
-- Nexar Admin debe leer con backend seguro y service_role en variables de entorno.
